version: '3.4'

services:
  wekanaccountslockout:
    image: wekanaccountslockout
    build:
      context: packages/wekan-accounts-lockout
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 80:80
